[default]
workshop = [
    "3499977893",
    "501966277"
]
dlc = [
    "vn"
]
mission = 'zombie_test.VR'
optionals = []
parameters = []
executable = "arma3_x64" # Default: "arma3_x64"
file_patching = true
binarize = false
rapify = true
