name = "Zombies and Demons - S.O.G. Prairie Fire compatibility"
prefix = "vnz"
mainprefix = "v"

[properties]
author = "Spoffy"
url = "https://www.sogpf.com"

[version]
major = 1
minor = 0
patch = 0

[release]
sign = true
archive = true

[files]
include = [

]
